sms_password: '575bf5a52d5e2d4a9d6957d2245c30c8'
sms_tpl_id: 1628154
weixin:
  api_id: wxafc43cbd018d7237
  api_secret: 2010d4939d948a6c715b8115704e677f
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: http://ybhm.ybyt.cc
  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://ybhm.ybyt.c/wechat"
        - type: "view"
          name: "我的"
          url: "http://ybhm.ybyt.c/wechat/my/my_info"
    - name: "御邦平行店"
      sub_button:
        - type: "view"
          name: "御邦平行店首页"
          url: "http://spddev.ybyt.cc/"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "龙氏脊筑服务"
          url: "http://spddev.ybyt.cc/"

external:
  api_url: http://120.25.81.41:10010/open_api/v1/
  app_id: 3ZwZPp85UT0CdHRXruKmZxlPkQEG7RXkCLZptNvUwhDRRQggdtR70WQq81S7MVSxpunyvCz3_2qxDRZlzbngGw==
  secret_key: EnjQnB1OFLozWnx78zyhslyAuTUSkqc46NStANW/RhmdiVwD8bWfKjhH9Mv4gULaQmr9+LI9Senwt8Lp0EeQSg==

fast_pay:
  url: http://openapi.yijifu.net/gateway.html
  secrect_key: 3e5509cd3ab2c0ca73cc178d274dcd33
  partner_id: 20160606020000748137
  host: "http://ybhm.ybyt.cc/"

device:
  secrect_key: ahutomsystem-yubangyt-jy

notification:
  exception_email_prefix: '[YBH mall production Exception]'
  exception_email_sender_address: '<yubangyitong@ybyt.cc>'
  notification_receivers:
    - 448426851@qq.com
    - yubangyitong@ybyt.cc
    - fangmingming@ybyt.cc
    - liujingjing@ybyt.cc
    - lijing@ybyt.cc

qq_lbs:
  url: http://apis.map.qq.com/ws/
  app_id: K32BZ-MDYKU-3A2V6-4QR4F-N23U3-QWF67
  secrect_key: vHpDX5JaWXjnZr2IJ3NHTUxoMIqzkUoN
