sms_password: '575bf5a52d5e2d4a9d6957d2245c30c8'
sms_tpl_id: 1628154
weixin:
  api_id: wxe96e65edf5433086
  api_secret: f66087db281933b1a7aa737535532a2f
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: https://xiao.localtunnel.me/

  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://ybhm.ybyt.c/wechat"
        - type: "view"
          name: "我的"
          url: "http://ybhm.ybyt.c/wechat/my/my_info"
    - name: "商城"
      sub_button:
        - type: "view"
          name: "商城首页"
          url: "http://spddev.ybyt.cc/"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "龙氏脊筑服务"
          url: "http://spddev.ybyt.cc/"

external:
  api_url: http://120.25.81.41:10010/open_api/v1/
  app_id: 3ZwZPp85UT0CdHRXruKmZxlPkQEG7RXkCLZptNvUwhDRRQggdtR70WQq81S7MVSxpunyvCz3_2qxDRZlzbngGw==
  secret_key: EnjQnB1OFLozWnx78zyhslyAuTUSkqc46NStANW/RhmdiVwD8bWfKjhH9Mv4gULaQmr9+LI9Senwt8Lp0EeQSg==

fast_pay:
  url: http://openapi.yijifu.net/gateway.html
  secrect_key: 3e5509cd3ab2c0ca73cc178d274dcd33
  partner_id: 20160606020000748137
  host: "http://ybhm.ybyt.cc/"
