weixin:
  api_id: wxe96e65edf5433086
  api_secret: f66087db281933b1a7aa737535532a2f
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: https://xiao.localtunnel.me/

  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://spddev.ybyt.cc/"
        - type: "view"
          name: "我的"
          url: "http://spddev.ybyt.cc/"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "我的服务"
          url: "http://spddev.ybyt.cc/"
        - type: "view"
          name: "服务"
          url: "http://spddev.ybyt.cc/"
    - name: "商城"
      sub_button:
        - type: "view"
          name: "热销产品"
          url: "http://spddev.ybyt.cc/"
        - type: "view"
          name: "我的订单"
          url: "http://spddev.ybyt.cc/"
