sms_password: '575bf5a52d5e2d4a9d6957d2245c30c8'
sms_tpl_id: 1628154
weixin:
  api_id: wxafc43cbd018d7237
  api_secret: 2010d4939d948a6c715b8115704e677f
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: http://ybhm.ybyt.cc

  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://ybhm.ybyt.cc/wechat"
        - type: "view"
          name: "我的"
          url: "http://ybhm.ybyt.cc/user"
    - name: "商城"
      sub_button:
        - type: "view"
          name: "商城首页"
          url: "http://ybhm.ybyt.cc/mall"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "服务首页"
          url: "http://ybhm.ybyt.cc/service"
        - type: "view"
          name: "健康检测"
          url: "http://ybhm.ybyt.cc/examine/home"
