weixin:
  api_id: wx2c5c597a0f025728
  api_secret: 506e3a9230b1f1005ad4ca942df0ad17
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: http://ybhm.ybyt.cc

  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://ybhm.ybyt.cc/wechat"
        - type: "view"
          name: "我的"
          url: "http://ybhm.ybyt.cc/wechat/user/info"
    - name: "商城"
      sub_button:
        - type: "view"
          name: "商城首页"
          url: "http://spddev.ybyt.cc/"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "龙氏脊筑服务"
          url: "http://spddev.ybyt.cc/"
