weixin:
  api_id: wx864eabd00376d47d
  api_secret: fba770719dd0fb1ddaad607156a8fae4
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: http://ybhm.ybyt.cc

  menu:
    button:
    - type: "view"
      name: "御邦会"
      sub_button:
        - type: "view"
          name: "首页"
          url: "http://ybhm.ybyt.c/wechat"
        - type: "view"
          name: "我的"
          url: "http://ybhm.ybyt.c/wechat/my/my_info"
    - name: "商城"
      sub_button:
        - type: "view"
          name: "商城首页"
          url: "http://spddev.ybyt.cc/"
    - name: "服务"
      sub_button:
        - type: "view"
          name: "龙氏脊筑服务"
          url: "http://spddev.ybyt.cc/"
