sms_password: '575bf5a52d5e2d4a9d6957d2245c30c8'
sms_tpl_id: 1628154
scoin_account_tpl_id: 1698562
register_tpl_id: 1810862
weixin:
  api_id: wxafc43cbd018d7237
  api_secret: 2010d4939d948a6c715b8115704e677f
  token: 9ea435f4ac0c6161f25d2253
  secret: iZoqfJJJjGtG6nq-yER_1Ipb7wAu5D6V
  host: http://ybhm.ybyt.cc

  menu:
    button:
    - type: "view"
      name: "御易健"
      url: "http://ybhm.ybyt.cc/wechat"
    - name: "御邦平行店"
      url: "http://ybhm.ybyt.cc/mall"
    - name: "我的"
      sub_button:
        - type: "view"
          name: "我的御易健"
          url: "http://ybhm.ybyt.cc/user"
#        - type: "view"
#          name: "一盏明灯"
#          url: "http://ybhm.ybyt.cc/wechat/light"
        - type: "view"
          name: "动态监测"
          url: "http://ybhm.ybyt.cc/user/moving_health_data"
        - type: "view"
          name: "健康娱乐"
          url: "http://qolm.ybyt.cc/_game/llk/"
        - type: "view"
          name: "客服服务"
          url: "http://ybhm.ybyt.cc/feedback"
#        - type: "view"
#          name: "疾病风险评估"
#          url: "http://ybhm.ybyt.cc/evaluate/index"


external:
  api_url: http://qolm.ybyt.cc/open_api/v1/
  app_id: 3ZwZPp85UT0CdHRXruKmZxlPkQEG7RXkCLZptNvUwhDRRQggdtR70WQq81S7MVSxpunyvCz3_2qxDRZlzbngGw==
  secret_key: EnjQnB1OFLozWnx78zyhslyAuTUSkqc46NStANW/RhmdiVwD8bWfKjhH9Mv4gULaQmr9+LI9Senwt8Lp0EeQSg==

fast_pay:
  url: <%= ENV['FAST_PAY_URL'] %>
  secrect_key: <%= ENV['FAST_PAY_KEY'] %>
  partner_id: <%= ENV['FAST_PAY_PARTNER_ID'] %>
  host: "http://ybhm.ybyt.cc/"
  # url: http://openapi.yijifu.net/gateway.html
  # secrect_key: 3e5509cd3ab2c0ca73cc178d274dcd33
  # partner_id: 20160606020000748137
  # host: "http://ybhm.ybyt.cc/"

idata:
  url: http://test.idata-power.com:7001/DRS/
  username: ybyt
  password: a2d61138548c11e79f9200163e00307f
  org_code: 063001
  own_username: 4dc4792efc5ce38c96ca7c89c27047f8
  own_password: 3835ea275ead062cbd409aa360c79478
  template_id: OK1JktRtESneUJOeuTuvaehdSM9aZlq51jI9xdBq8Pg
